import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Mubasshir</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Mubasshir Ahmed</h1>
      </main>
    </>
  );
}
