import Head from 'next/head';
import profilePic from '../public/images/profile/p-m-h.png';
import AnimatedImage from '/src/components/AnimatedImage';
import AnimatedParagraph from '/src/components/AnimatedParagraph';
import AnimatedSubText from '/src/components/AnimatedSubText';
import AnimatedText from '/src/components/AnimatedText';
import HeroButtons from '/src/components/HeroButtons';
import Layout from '/src/components/Layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Mubasshir</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex  items-center dark:bg-[#18191A] text-black dark:text-light w-full min-h-screen">
        <Layout className="xl:pt-0 lg:pt-16 md:pt-10 sm:pt-6">
          <div className="hero-section flex  items-center justify-between w-full ">
            <div className="hero-text w-1/2 flex flex-col items-center self-center">
              <AnimatedSubText
                text="I'm Mubasshir,"
                className="dark:text-transparent dark:bg-clip-text dark:bg-gradient-to-r from-pink-600 to-red-600 dark:duration-300"
              />
              <AnimatedText
                text="Let's Turn Vision Into Reality With The Magic Of React..."
                className=" !text-left !leading-[64px] dark:text-white/80
xl:!text-6xl lg:text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
                "
              />
              <AnimatedParagraph
                text="As a react developer, my passion is to transform ideas into dynamic and efficient web applications with a strong attention to detail. Explore my latest projects, which showcase my proficiency in web-development."
                className=""
              />
              <div className="hero-buttons flex items-center mt-2  self-start">
                <HeroButtons className="hero-buttons flex items-center mt-4 self-start" />
              </div>
            </div>

            <div className="hero-image w-1/2">
              <AnimatedImage
                src={profilePic}
                alt="React developer: Mubasshir Ahmed"
                className="w-full h-auto
                sm:hidden md:inline-block md:w-full
                "
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
